apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svelte-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: bubblematch.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svelte-app-service
            port:
              number: 5173

  - host: api.bubblematch.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bmatch-gateway-service
            port:
              number: 8002
